# Generated by Django 2.0.3 on 2020-05-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bimglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
                ('firstimage', models.TextField(blank=True, max_length=1000, null=True)),
                ('secondimage', models.TextField(blank=True, max_length=1000, null=True)),
                ('thirthimage', models.TextField(blank=True, max_length=1000, null=True)),
                ('fourthimage', models.TextField(blank=True, max_length=1000, null=True)),
                ('fiveimage', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CateEarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_nl', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_de', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_es', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_nl', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_de', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_es', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedef', models.IntegerField(blank=True, null=True)),
                ('totaltime', models.TextField(blank=True, max_length=1000, null=True)),
                ('calismaalani', models.IntegerField(blank=True, null=True)),
                ('kilotipi', models.IntegerField(blank=True, null=True)),
                ('guctipi', models.IntegerField(blank=True, null=True)),
                ('guntipi', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_nl', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_de', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_es', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_nl', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_de', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_es', models.TextField(blank=True, max_length=1000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Programfordaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setcount', models.IntegerField(blank=True, null=True)),
                ('replycount', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('isitrest', models.BooleanField(verbose_name='isitrest')),
                ('isitduration', models.BooleanField(verbose_name='isitduration')),
                ('orderlist', models.IntegerField(blank=True, null=True)),
                ('weeknumber', models.IntegerField(blank=True, null=True)),
                ('daynumber', models.IntegerField(blank=True, null=True)),
                ('overprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DailyProgram')),
                ('progrm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Programlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setcount', models.IntegerField(blank=True, null=True)),
                ('replycount', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('orderlist', models.IntegerField(blank=True, null=True)),
                ('isitduration', models.BooleanField(default=True, verbose_name='isitduration')),
                ('isitrest', models.BooleanField(verbose_name='isitrest')),
                ('progrm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, max_length=1000, null=True)),
                ('totaltime', models.TextField(blank=True, max_length=1000, null=True)),
                ('place', models.TextField(blank=True, max_length=1000, null=True)),
                ('isitpremium', models.BooleanField(verbose_name='premium')),
                ('name_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_nl', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_de', models.TextField(blank=True, max_length=1000, null=True)),
                ('name_es', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_en', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_tr', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_nl', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_de', models.TextField(blank=True, max_length=1000, null=True)),
                ('explain_es', models.TextField(blank=True, max_length=1000, null=True)),
                ('Ctgry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubtitleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.TextField(blank=True, max_length=1000, null=True)),
                ('language', models.TextField(blank=True, max_length=1000, null=True)),
                ('forwhichprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptData', models.TextField(blank=True, max_length=1000, null=True)),
                ('TierPrice', models.TextField(blank=True, max_length=1000, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookid', models.CharField(blank=True, max_length=1000, null=True)),
                ('gmailid', models.CharField(blank=True, max_length=1000, null=True)),
                ('phonetype', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('surname', models.CharField(blank=True, max_length=1000, null=True)),
                ('notification', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=1000, null=True)),
                ('kilo', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('btype', models.IntegerField(blank=True, null=True)),
                ('usertype', models.IntegerField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=1000, null=True)),
                ('place', models.CharField(blank=True, max_length=1000, null=True)),
                ('traindayinweek', models.CharField(blank=True, max_length=1000, null=True)),
                ('profilephoto', models.FileField(blank=True, null=True, upload_to='')),
                ('birthday', models.DateTimeField(null=True)),
                ('deviceid', models.CharField(blank=True, max_length=1000, null=True)),
                ('premium', models.DateTimeField(blank=True, null=True)),
                ('setsayisi', models.IntegerField(blank=True, null=True)),
                ('suresayisi', models.IntegerField(blank=True, null=True)),
                ('strongorlight', models.IntegerField(blank=True, null=True)),
                ('isitpremium', models.BooleanField(verbose_name='premium')),
                ('dailyprogramdetail', models.IntegerField(blank=True, null=True)),
                ('lasttenhours', models.DateTimeField(null=True)),
                ('onemonthlater', models.DateTimeField(null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='Buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='programlist',
            name='psc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubCategory'),
        ),
        migrations.AddField(
            model_name='cateearn',
            name='EarnerUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='cateearn',
            name='Subcate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubCategory'),
        ),
    ]
